import { NextRequest, NextResponse } from 'next/server'
import { createSupabaseServerClient } from '@/lib/supabase/server'

export const runtime = 'nodejs'

// Handles both the email-confirmation link from sign-up and any magic
// link / invite link generated by app/api/admin/invite/route.ts. In every
// case we exchange the ?code= for a session, then try to claim the
// ship.profiles row (a no-op if it was already claimed, e.g. during
// sign-up before confirmation was required).
export async function GET(request: NextRequest) {
  const { searchParams, origin } = new URL(request.url)
  const code = searchParams.get('code')

  if (!code) {
    return NextResponse.redirect(`${origin}/`)
  }

  const supabase = await createSupabaseServerClient()
  const { error: exchangeError } = await supabase.auth.exchangeCodeForSession(code)

  if (exchangeError) {
    return NextResponse.redirect(`${origin}/`)
  }

  // A 42501 here just means there's no matching pending_invites row for
  // this email — ignore it, since the user may already have a profile
  // from an earlier successful claim (e.g. on sign-up, before email
  // confirmation was required).
  const { error: claimError } = await supabase.rpc('claim_invite')
  if (claimError && claimError.code !== '42501') {
    console.error('claim_invite failed in auth callback:', claimError)
  }

  const {
    data: { user },
  } = await supabase.auth.getUser()

  if (user) {
    const { data: profile } = await supabase
      .from('profiles')
      .select('id')
      .eq('id', user.id)
      .maybeSingle()

    if (profile) {
      return NextResponse.redirect(`${origin}/projects`)
    }
  }

  return NextResponse.redirect(`${origin}/no-access`)
}
