import { LineItem } from './types'

export const SEED_LINE_ITEMS: LineItem[] = [
  {
    id: 'seed-li-001',
    projectId: 'federal-campus-master-plan',
    userEmail: 'admin@gmail.com',
    consultantType: 'Architecture',
    companyName: 'FAA',
    discipline: 'Architecture',
    itemNumber: 'A1',
    name: 'Campus Arrival Sequence Upgrade',
    shortDescription: 'Rework front-of-house arrival, screening, and lobby circulation.',
    category: 'UPGRADES / IMPROVEMENTS',
    timelinePriority: '1_HIGH <5 years',
    buildingAreaImpacted: 'SITE',
    buildingLevelImpacted: 'WHOLE BUILDING',
    operationalImpact: 'MODERATE',
    benefitToUsers: 'HIGH',
    benefitToPublic: 'MODERATE',
    relativeFirstCost: '$$$High',
    estimatedFirstCost: '$2,400,000',
    relativeOperationCostImpact: 'MINIMAL IMPACT',
    relativeOperationalEnergyUsage: 'MINIMAL IMPACT',
    electrificationEO594: 'LOW',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'No',
    codeLifeSafetyImprovement: 'Yes',
    accessibilityImprovement: 'Yes',
    historicImpact: 'No',
    potentialSynergies: ['Civil', 'Landscape', 'Security'],
    supportingNotes: 'Coordinate entry canopy, site grading, and queueing.',
    createdAt: '2026-04-01T09:00:00.000Z',
  },
  {
    id: 'seed-li-002',
    projectId: 'federal-campus-master-plan',
    userEmail: 'planning@atlasmech.com',
    consultantType: 'Mechanical',
    companyName: 'Atlas MEP',
    discipline: 'Mechanical',
    itemNumber: 'M1',
    name: 'Central Plant Decarbonization',
    shortDescription: 'Replace aging boilers with electric heat pump plant.',
    category: 'END OF LIFE',
    timelinePriority: '0_PRIORITY *',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'LEVELS BELOW GRADE',
    operationalImpact: 'HIGH',
    benefitToUsers: 'MODERATE',
    benefitToPublic: 'HIGH',
    relativeFirstCost: '$$$High',
    estimatedFirstCost: '$6,800,000',
    relativeOperationCostImpact: 'HIGH REDUCTION',
    relativeOperationalEnergyUsage: 'HIGH REDUCTION',
    electrificationEO594: 'HIGH',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'Yes',
    codeLifeSafetyImprovement: 'No',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Electrical', 'Structural'],
    supportingNotes: 'Phasing required to maintain heating through winter.',
    createdAt: '2026-04-01T09:15:00.000Z',
  },
  {
    id: 'seed-li-003',
    projectId: 'federal-campus-master-plan',
    userEmail: 'structural@coredesign.com',
    consultantType: 'Structural',
    companyName: 'Core Design Structures',
    discipline: 'Structural',
    itemNumber: 'S1',
    name: 'Roof Framing Reinforcement',
    shortDescription: 'Targeted strengthening for mechanical yard and solar loads.',
    category: 'DEFERRED MAINTENANCE',
    timelinePriority: '1_HIGH <5 years',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'ROOF',
    operationalImpact: 'LOW',
    benefitToUsers: 'LOW',
    benefitToPublic: 'LOW',
    relativeFirstCost: '$$Moderate',
    estimatedFirstCost: '$1,150,000',
    relativeOperationCostImpact: 'N/A',
    relativeOperationalEnergyUsage: 'N/A',
    electrificationEO594: 'LOW',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'Yes',
    codeLifeSafetyImprovement: 'Yes',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Mechanical', 'Electrical'],
    supportingNotes: 'Sequence with roof replacement and photovoltaic work.',
    createdAt: '2026-04-01T09:30:00.000Z',
  },
  {
    id: 'seed-li-004',
    projectId: 'federal-campus-master-plan',
    userEmail: 'electrical@voltworks.com',
    consultantType: 'Electrical',
    companyName: 'Volt Works',
    discipline: 'Electrical',
    itemNumber: 'E1',
    name: 'Emergency Power Renewal',
    shortDescription: 'Upgrade generators, ATS gear, and distribution redundancy.',
    category: 'END OF LIFE',
    timelinePriority: '0_PRIORITY *',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'LEVELS BELOW GRADE',
    operationalImpact: 'HIGH',
    benefitToUsers: 'HIGH',
    benefitToPublic: 'MODERATE',
    relativeFirstCost: '$$$High',
    estimatedFirstCost: '$3,250,000',
    relativeOperationCostImpact: 'MINIMAL IMPACT',
    relativeOperationalEnergyUsage: 'N/A',
    electrificationEO594: 'MODERATE',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'Yes',
    codeLifeSafetyImprovement: 'Yes',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Mechanical', 'Architecture'],
    supportingNotes: 'Coordinate outage windows with tenant operations.',
    createdAt: '2026-04-01T09:45:00.000Z',
  },
  {
    id: 'seed-li-005',
    projectId: 'federal-campus-master-plan',
    userEmail: 'civil@terrainlab.com',
    consultantType: 'Civil',
    companyName: 'Terrain Lab',
    discipline: 'Civil',
    itemNumber: 'C1',
    name: 'Stormwater Resilience Package',
    shortDescription: 'Bioswales, detention, and site drainage replacement.',
    category: 'UPGRADES / IMPROVEMENTS',
    timelinePriority: '2_MID 5-10 years',
    buildingAreaImpacted: 'SITE',
    buildingLevelImpacted: 'WHOLE BUILDING',
    operationalImpact: 'MODERATE',
    benefitToUsers: 'LOW',
    benefitToPublic: 'HIGH',
    relativeFirstCost: '$$Moderate',
    estimatedFirstCost: '$1,980,000',
    relativeOperationCostImpact: 'MINIMAL IMPACT',
    relativeOperationalEnergyUsage: 'N/A',
    electrificationEO594: 'NONE',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'Yes',
    codeLifeSafetyImprovement: 'No',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Landscape', 'Architecture'],
    supportingNotes: 'Integrate with plaza reconstruction and planting upgrades.',
    createdAt: '2026-04-01T10:00:00.000Z',
  },
  {
    id: 'seed-li-006',
    projectId: 'federal-campus-master-plan',
    userEmail: 'historic@heritagestudio.com',
    consultantType: 'Historic Preservation',
    companyName: 'Heritage Studio',
    discipline: 'Historic Preservation',
    itemNumber: 'HP1',
    name: 'Stone Facade Conservation',
    shortDescription: 'Repair masonry, lintels, sealants, and ornamental stone.',
    category: 'RESTORATION *',
    timelinePriority: '1_HIGH <5 years',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'ENVELOPE (EXT. WALLS)',
    operationalImpact: 'LOW',
    benefitToUsers: 'MODERATE',
    benefitToPublic: 'HIGH',
    relativeFirstCost: '$$$High',
    estimatedFirstCost: '$4,300,000',
    relativeOperationCostImpact: 'MINIMAL IMPACT',
    relativeOperationalEnergyUsage: 'MINIMAL IMPACT',
    electrificationEO594: 'NONE',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'Yes',
    codeLifeSafetyImprovement: 'No',
    accessibilityImprovement: 'No',
    historicImpact: 'Yes',
    potentialSynergies: ['Architecture', 'Structural'],
    supportingNotes: 'Requires mockups and preservation review.',
    createdAt: '2026-04-01T10:15:00.000Z',
  },
  {
    id: 'seed-li-007',
    projectId: 'federal-campus-master-plan',
    userEmail: 'access@openpath.com',
    consultantType: 'Accessibility',
    companyName: 'Open Path',
    discipline: 'Accessibility',
    itemNumber: 'AC1',
    name: 'Accessible Vertical Circulation Refresh',
    shortDescription: 'Upgrade elevator cab controls, wayfinding, and refuge signage.',
    category: 'UPGRADES / IMPROVEMENTS',
    timelinePriority: '1_HIGH <5 years',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'LEVELS ABOVE GRADE',
    operationalImpact: 'LOW',
    benefitToUsers: 'HIGH',
    benefitToPublic: 'LOW',
    relativeFirstCost: '$$Moderate',
    estimatedFirstCost: '$820,000',
    relativeOperationCostImpact: 'N/A',
    relativeOperationalEnergyUsage: 'N/A',
    electrificationEO594: 'NONE',
    addressingResiliencySustainability: 'No',
    addressingDeferredMaintenance: 'No',
    codeLifeSafetyImprovement: 'Yes',
    accessibilityImprovement: 'Yes',
    historicImpact: 'No',
    potentialSynergies: ['Architecture', 'Electrical'],
    supportingNotes: 'Coordinate with elevator modernization sequence.',
    createdAt: '2026-04-01T10:30:00.000Z',
  },
  {
    id: 'seed-li-008',
    projectId: 'federal-campus-master-plan',
    userEmail: 'landscape@fieldoffice.com',
    consultantType: 'Landscape',
    companyName: 'Field Office',
    discipline: 'Landscape',
    itemNumber: 'L1',
    name: 'Perimeter Security Landscape Buffer',
    shortDescription: 'Rework planting and low walls at public perimeter.',
    category: 'UPGRADES / IMPROVEMENTS',
    timelinePriority: '2_MID 5-10 years',
    buildingAreaImpacted: 'SITE',
    buildingLevelImpacted: 'WHOLE BUILDING',
    operationalImpact: 'LOW',
    benefitToUsers: 'MODERATE',
    benefitToPublic: 'MODERATE',
    relativeFirstCost: '$$Moderate',
    estimatedFirstCost: '$640,000',
    relativeOperationCostImpact: 'MINIMAL IMPACT',
    relativeOperationalEnergyUsage: 'N/A',
    electrificationEO594: 'NONE',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'No',
    codeLifeSafetyImprovement: 'No',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Civil', 'Architecture'],
    supportingNotes: 'Coordinate with stormwater package.',
    createdAt: '2026-04-01T10:45:00.000Z',
  },
  {
    id: 'seed-li-009',
    projectId: 'federal-campus-master-plan',
    userEmail: 'admin@gmail.com',
    consultantType: 'Architecture',
    companyName: 'FAA',
    discipline: 'Architecture',
    itemNumber: 'A2',
    name: 'Workplace Restack and Swing Space',
    shortDescription: 'Multi-floor phased restack to unlock renovation moves.',
    category: 'STUDY / DOCUMENTATION',
    timelinePriority: '0_PRIORITY *',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'LEVELS ABOVE GRADE',
    operationalImpact: 'MODERATE',
    benefitToUsers: 'HIGH',
    benefitToPublic: 'LOW',
    relativeFirstCost: '$$Moderate',
    estimatedFirstCost: '$950,000',
    relativeOperationCostImpact: 'INCREASE',
    relativeOperationalEnergyUsage: 'N/A',
    electrificationEO594: 'NONE',
    addressingResiliencySustainability: 'No',
    addressingDeferredMaintenance: 'No',
    codeLifeSafetyImprovement: 'No',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Mechanical', 'Electrical', 'Accessibility'],
    supportingNotes: 'Needed to support central plant and life safety work.',
    createdAt: '2026-04-01T11:00:00.000Z',
  },
  {
    id: 'seed-li-010',
    projectId: 'federal-campus-master-plan',
    userEmail: 'electrical@voltworks.com',
    consultantType: 'Electrical',
    companyName: 'Volt Works',
    discipline: 'Electrical',
    itemNumber: 'E2',
    name: 'Lighting and Controls Modernization',
    shortDescription: 'Campus-wide LED conversion and occupancy/daylight controls.',
    category: 'UPGRADES / IMPROVEMENTS',
    timelinePriority: '2_MID 5-10 years',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'LEVELS ABOVE GRADE',
    operationalImpact: 'MODERATE',
    benefitToUsers: 'MODERATE',
    benefitToPublic: 'LOW',
    relativeFirstCost: '$$Moderate',
    estimatedFirstCost: '$1,420,000',
    relativeOperationCostImpact: 'MODERATE REDUCTION',
    relativeOperationalEnergyUsage: 'HIGH REDUCTION',
    electrificationEO594: 'MODERATE',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'Yes',
    codeLifeSafetyImprovement: 'No',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Architecture', 'Mechanical'],
    supportingNotes: 'Best grouped by floor swing package.',
    createdAt: '2026-04-01T11:15:00.000Z',
  },
  {
    id: 'seed-li-011',
    projectId: 'federal-campus-master-plan',
    userEmail: 'planning@atlasmech.com',
    consultantType: 'Mechanical',
    companyName: 'Atlas MEP',
    discipline: 'Mechanical',
    itemNumber: 'M2',
    name: 'Floor-by-Floor Airside Renewal',
    shortDescription: 'Replace VAVs, branch ductwork, and floor distribution by phase.',
    category: 'DEFERRED MAINTENANCE',
    timelinePriority: '2_MID 5-10 years',
    buildingAreaImpacted: 'WHOLE BUILDING',
    buildingLevelImpacted: 'LEVELS ABOVE GRADE',
    operationalImpact: 'HIGH',
    benefitToUsers: 'HIGH',
    benefitToPublic: 'LOW',
    relativeFirstCost: '$$$High',
    estimatedFirstCost: '$5,600,000',
    relativeOperationCostImpact: 'MODERATE REDUCTION',
    relativeOperationalEnergyUsage: 'MODERATE REDUCTION',
    electrificationEO594: 'LOW',
    addressingResiliencySustainability: 'Yes',
    addressingDeferredMaintenance: 'Yes',
    codeLifeSafetyImprovement: 'No',
    accessibilityImprovement: 'No',
    historicImpact: 'No',
    potentialSynergies: ['Electrical', 'Architecture'],
    supportingNotes: 'Link to phased workplace restack and controls package.',
    createdAt: '2026-04-01T11:30:00.000Z',
  },
  {
    id: 'seed-li-012',
    projectId: 'federal-campus-master-plan',
    userEmail: 'admin@gmail.com',
    consultantType: 'Architecture',
    companyName: 'FAA',
    discipline: 'Architecture',
    itemNumber: 'A3',
    name: 'Public Meeting Center Renovation',
    shortDescription: 'Reconfigure ceremonial and public-facing event rooms.',
    category: 'UPGRADES / IMPROVEMENTS',
    timelinePriority: '3_LOW 10-20 years',
    buildingAreaImpacted: 'ANNEX',
    buildingLevelImpacted: 'L1',
    operationalImpact: 'LOW',
    benefitToUsers: 'HIGH',
    benefitToPublic: 'HIGH',
    relativeFirstCost: '$$Moderate',
    estimatedFirstCost: '$1,780,000',
    relativeOperationCostImpact: 'MINIMAL IMPACT',
    relativeOperationalEnergyUsage: 'MINIMAL IMPACT',
    electrificationEO594: 'NONE',
    addressingResiliencySustainability: 'No',
    addressingDeferredMaintenance: 'No',
    codeLifeSafetyImprovement: 'Yes',
    accessibilityImprovement: 'Yes',
    historicImpact: 'Yes',
    potentialSynergies: ['Historic Preservation', 'Electrical', 'Accessibility'],
    supportingNotes: 'Could be split into enabling and fit-out phases.',
    createdAt: '2026-04-01T11:45:00.000Z',
  },
]
